[package]
name = "rust-scheduler-notify"
version = "0.1.0"
edition = "2021"

[dependencies]
clokwerk = "0.4.0"
notify-rust = "4.11.3"
mio = "0.8.11"
tokio = { version = "1.41.1", features = ["full"] }
