apiVersion: microservices.application.io/v1alpha1
kind: SchedulerConfig
spec:
  services:
    - name: "list-files"
      binary: ls
      cron: "45 * * * * *"
      summary: "List Files"
      body: "check current directory"
      icon: "firefox"
      env:
        - name: LOG_LEVEL
          value: TRACE
      args:
        - name: ""
          value: "-la"
